### ISSUE TITLE
Allow for requests coming from Kale to be tracked for analytics purposes

### ISSUE THREAD

**Issue by cjgala** [IBM-Watson/kale#10]
Request from Jerome to somehow track Kale usage and which service calls are made using Kale.

Need to coordinate with other teams. Initial thought was to add an extra CGI parameter consistently to all API requests. This param would be ignored by the services and accessible via logs.

**Comment by michaelkeeling** [comment]
To do this we're going to specify the client, Java version, and OS as reported by Java, in the `user-agent` field in the header.  The field might look something like...

```
kale_cli/1.0.0 (java.vendor=Oracle Corporation; os.arch=x86_64; os.version=10.11.4; os.name=Mac OS X; java.version=1.8.0_66)
```

**Comment by bruceadams** [comment]
The Data Crawler has a User-Agent header that looks like this:

```
User-Agent: crawler/0.1.25-dev+rwmoore-4-gd1bb828 (java.vendor=Oracle Corporation; os.arch=amd64; os.version=3.13.0-85-generic; os.name=Linux; java.version=1.8.0_91)
```

I'm presuming we want to have `kale` produce a similar looking thing.

**Comment by bruceadams** [comment]
OK. `kale` is sending User-Agent strings that look like this:

```
ibm-watson-kale/1.5.0-SNAPSHOT (os.arch=x86_64; os.name=Mac OS X; os.version=10.11.5; java.version=1.8.0_91; java.vendor=Oracle Corporation)
```
