### ISSUE TITLE
Kale cannot connect to Bluemix staging using TLSv1

### ISSUE THREAD

**Issue by cjgala** [IBM-Watson/kale#17]
The Bluemix staging environment was updated to no longer support TLSv1 API calls. This impacts Kale because some versions of java (including IBM Java 1.8) still perform the initial SSL handshake using TLSv1. When this happens, the following error message is returned.

> A call to: https://api.stage1.ng.bluemix.net triggered an unexpected exception: java.io.EOFException: SSL peer shut down incorrectly

One workaround is to just not use a version of java that make this handshake using a newer version. A better solution would be something that can be applied for any version of java (assuming they support newer versions of TLS).

**Comment by cjgala** [comment]
This problem appears to be specific to IBM Java and the underlying cause is IBM Java's TLS ClientHello message _always_ sending TLS v1.0, even when it has been told to only use TLS v1.2. Bluemix Staging will abort a TLS session if the client does not say it can handle TLS v1.2 in the ClientHello message.

**Comment by bruceadams** [comment]
I opened an issue against Apache HttpClient about this https://issues.apache.org/jira/browse/HTTPCLIENT-1784

Then, figured out a resolution, from the IBM Java documentation http://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/matchsslcontext_tls.html

We _may_ be able to work around this with `kale` by setting the Java System Property `com.ibm.jsse2.overrideDefaultTLS` to `true`.
