### ISSUE TITLE
Use CLA Assistant instead of a mailed-in CLA

### ISSUE THREAD

**Issue by colindean** [IBM-Watson/kale#20]
http://github.com/watson-developer-cloud/java-sdk is using it, so Kale probably can.

https://cla-assistant.io/watson-developer-cloud/java-sdk

https://cla-assistant.io/ <- seems pretty easy to set up.

**Comment by michaelkeeling** [comment]
This is what we were told to do by the legal team.  The verbiage is an "implicit cla" and does not require a contributor to take any action.

> By submitting any contributions to this project implicitly 
> you agree to the terms of the contributors license agreement located in the file CLA.md.

**Comment by bruceadams** [comment]
What confuses me is the text:

> By submitting any contributions to this project implicitly you agree to the terms of the contributors license agreement located in the file CLA.md.

appears to contradict the text _within_ CLA.md:

> ... IBM must have a Contributor License Agreement ("CLA") on file that has been signed by each Contributor ...

**Comment by cjgala** [comment]
Consulted with Terry, and he indicated we should be using the DCO rather than the CLA.  In the example that Colin linked, they are actually presenting the DCO using CLA Assistant.  I would think we should be able to do things the same way.

**Comment by cjgala** [comment]
The DCO was added to the repository (in the CONTRIBUTING.md file), and now a user has to agree to the DCO before their pull request is merged.
