### ISSUE TITLE
Don't enforce cluster size limits in `kale`

### ISSUE THREAD

**Issue by bruceadams** [IBM-Watson/kale#58]
The maximum cluster size is increasing sometime soon (from 7 to 14). There is no need for `kale` itself to enforce any size limit, since the R&R service gives a legible error message for exceeding size limits.

> WRRCSC003: The provided Solr cluster configuration contained a cluster_size [8] that was outside of the valid range ([1]-[7]).

**Comment by bberk041** [comment]
I will need to update some tests when this change is available.

**Comment by bruceadams** [comment]
This is fixed by #65
